[images]
  remote_patterns = [
    { protocol = "https", hostname = "ext.same-assets.com", pathname = "/**" },
    { protocol = "https", hostname = "ugc.same-assets.com", pathname = "/**" },
    { protocol = "https", hostname = "source.unsplash.com", pathname = "/**" },
    { protocol = "https", hostname = "images.unsplash.com", pathname = "/**" }
  ]

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
